version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - /tmp/postgres/data2:/var/lib/postgresql/data
      - ./quarkus-demo/src/main/resources/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:8.0.1
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  webserver:
    build: 
      context: ./webserver
    container_name: webserver
    ports:
      - "9090:8080"
    volumes:
      - ./webserver/files:/app

volumes:
  mongo_data: