services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - /tmp/postgres/data2:/var/lib/postgresql/data
      - ./quarkus-demo/src/main/resources/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:8.0.1
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local
